sudo: false
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
    - upx
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc build --only-dependencies
script:
- stack --no-terminal install --haddock --no-haddock-deps
before_deploy:
- cd ~/.local/bin
- upx ./kona
- tar cJf kona-linux-x64.tar.xz ./kona
deploy:
  provider: releases
  api_key:
    secure: RJet7+z3BU+ZwiDoRgToTBz+x7PT8QiCAlPsmHYhnyIXE3MS2vo7RlfIBqBINCxmwU5vhYR3oht9JXBcCO55SNLZBdhkxHUoXCK23wpj3dylsI8mQCBxinb5Mf4rp//Gg96LcyJErz3JXhdIvHPCHsHTA21NC9sEU3xvldzVMBuDEI/DgZsNjFScJkfg8OFl2ee4hPkvxoXoTj4Nvaut+dCHlUSYL3JRtGU3yByLpbM45ZT4wIw8hmavANC33kzU+cX9kfCM2ryT+6wRhKJXgiDZL7kTD69IpNQdRFegIgUy/8sanWwqSNRIkGsuz4b/xezYAxBcfDQRkSDzHJcYJkFTs810HYG792sRkOGjThAU8Ctono/+XAw9qA80Vfb+ukWEj1C4TBS1pbp32QOF9//1ui+aouDN67iU657Fw4EaMvNN6r0f4vdM8aJXYypewoTjUyY6ha9dhnYu6OBo7edDOYH3z568oej+hqwOAYdJI/hUUcOvAj2ql9mkWhAjCYOJz81asbQ3d7MidzIAN14isEpYJHVaLr5ghhZ41Jkt+4kAz+84sIBiAV90RkSVC4N56hlKlVkG9QCAiFx7M8mbpwCZ0o0t7hdf39DhdP4W/xUF3KnraKjQmBl9/X9sks1wuysXqEoSamHoj12XrN2hz3swuinysKrq6NwWcfY=
  file: kona-linux-x64.tar.xz
  on:
    tags: true
    repo: inflation/kona.hs
notifications:
  email: false
  slack:
    secure: efBHxJQ2MP4OK1ytQpcsRC1D9WIq/ctt81jG0/uOZ0UIc9rU4nN/AcwMnW7XVgi3Ptw1Zk6DJQue1QxZEcU4r+LDRAIwJyI8RVnyU5hgFmjPMtcw+oDE9WyDyGAV77pDDckPo3+0N3N42H8UiLeggsMz2MG50hmBZF5D01z971UH4f9nO0E8oYkACAAxxn8cG+uDBHZGN4hHyxML4hckSxv8pQf0VTAZ6qahWhaFkqm03UI4wjfpSMQoLTQsSiKHI1Ex580l+mKbiBekJtrRLXHuG6z0NqiMgzTgCKfdWQ6EZBRdgzuotkoEySA/u+PoKlEPR31F91GZyrmtlfuFuz9dcdbH3C8TQ7lbVh9lVGFZHLPOax4Cx6FQKXu3MqjE5IRzrTcWx9LkjHuNFiGJeuDTbrywapEflY2yPsFOvs3K3OOhpspkgV1opEt6ZQjl+vTRq840EcXGCHQsOguHOfvZpRw1bvTzALuz2MU6yOx/cX2rlZhJZZL2XDtua2Rt/BxS6m7q9URkVtdjAu+zlZWtzS19Ch9k+pEFPXGVw05tC0dipYcCKK4Au0RY6je3+aam9J5kFecWnyzvQ+Sg61D5UbSDkv/dcviXF94J+fJjQzfAFCof5wGkaUvlbJSvtrU46mHD1iFXxoNuUGO/NpIk/0LyZ1k32RR1SyEYz9E=
    on_success: change
    on_failure: always
